# Generated by Django 3.1.3 on 2020-11-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_experience', models.TextField()),
            ],
            options={
                'verbose_name': 'Опыт работы и практика',
                'verbose_name_plural': 'Опыт работы и практика',
            },
        ),
        migrations.CreateModel(
            name='MyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250)),
                ('service_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Моя услуга',
                'verbose_name_plural': 'Мои услуги',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Цены на мои услуги',
                'verbose_name_plural': 'Цены на мои услуги',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_photo', models.ImageField(upload_to='my_photo/')),
                ('my_name', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=30)),
                ('about_me', models.TextField()),
                ('my_citi', models.CharField(max_length=30)),
                ('contacts', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Мое фото+контакты',
                'verbose_name_plural': 'Мое фото+контакты',
            },
        ),
    ]
