# Generated by Django 3.1.3 on 2020-11-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['name_service'], 'verbose_name': 'Цены на мои услуги', 'verbose_name_plural': 'Цены на мои услуги'},
        ),
    ]
